### ISSUE TITLE
The project support tikz?

### ISSUE THREAD

**Issue by carveybunt** [tani/markdown-it-mathjax3#53]
I wanna use your project to draw the diagram of math. Does it support tikz?

**Comment by Dragon1573** [comment]
@carveybunt Tani 这位扩展原作者的定位信息写的是 **Japan** ，如果你真的为了方便他，请与他用日语交流。

不过在整个 GitHub 中，来自世界各地的用户都有，而英语是全球范围内用户最广泛的。如果你不会英语，那么就使用英语吧。

当然我也有关注 Tani ，所以你也可以使用中英双语（写汉语，然后机翻英语）的方式进行我们自己内部的交流。

*****

@tani There's an issue which using Simplified Chinese instead of English. If you think it violates the community guidelines, please mark it or just remove it. Thank you!

The requests of @carveybunt is as follows:

> Does this Markdown-it extension support `tikz`? I want to use it for drawing images, but I failed using like that directly ...

I don't know about `tikz`, could you please offer @carveybunt a help?

**Comment by carveybunt** [comment]
@Dragon1573 thanks.

**Comment by tani** [comment]
The functionality of this plugin heavily relies on MathJax. All of the supported latex packages are listed on https://github.com/mathjax/MathJax-src/tree/master/components/src/input/tex/extensions . According to the list, there are no tikz for MathJax. However,
you can use a smaller part of tikz functionality by alternative packages.

To reduce the duplicated report, other users can easily find the same issue if you write it in English. This is a great contribution to the community. Please try it.

@Dragon1573 Thank you for the assistance. As you said I am Japanese who is not use English for daily communication. So I have an empathy that we prefer to speak our own native language. Personally, I had learned Chinese a few years ago, so that I enjoyed reading it.

谢谢 :)

**Comment by carveybunt** [comment]
Thanks for your reply.

**Comment by tani** [comment]
Cheers 🍻
