### ISSUE TITLE
How to add equation numbering?

### ISSUE THREAD

**Issue by LwRuan** [tani/markdown-it-mathjax3#55]
Mathjax seems to support automatic equation numbering: http://docs.mathjax.org/en/latest/input/tex/eqnumbers.html#, it's possible to turn this on in config?

**Comment by tani** [comment]
Thanks for asking me. Since v4.0.0, you can use this feature as follows.

```js
var md = require('markdown-it')()
var mathjax3 = require('markdown-it-mthjax3')
md.use(mathjax3, { tex: { tags: 'ams' }})
```

Please close this issue if you have no problem.

**Comment by Dragon1573** [comment]
Upgraded to `v4.0.0` (https://github.com/Dragon1573/Study-Notes/commit/3f80ea8f59df7a125521f97c9fdb142e0e3c77aa) and enabled automatic equation numbering an hour ago (https://github.com/Dragon1573/Study-Notes/commit/324dc88ade6f9ed0fb0de2a37a7800ac1fe7ef5f).

Everything looks good! It seems that Mathjax3 will only numbering those "multi-line" equation groups. If the equation only has one line, it won't be numbered.

![image](https://user-images.githubusercontent.com/49941141/149775985-1b52b6a9-146b-4957-8ffd-9d04f244a10f.png)

**Comment by LwRuan** [comment]
Thanks!

**Comment by BIKA-C** [comment]
Hey…  Is there a way to call the [`MathJax.texReset()`](https://docs.mathjax.org/en/latest/web/typeset.html#resetting-automatic-equation-numbering) using this plugin so that it resets the numbering? I couldn't get an access to the MathJax instance and It keeps complaining that MathJax is not defined...

**Comment by tani** [comment]
@BIKA-C There are three ways to use MathJax from JavaScript. 
1． To define a constant `MathJax` in the global scope and use it 
2. To call a Component API provided by MathJax 
3. To call MathJax functions directly.

This library uses the third method. Therefore, no `MathJax` constants are defined. Commonly. you do not need to call the function `texReset()` because the numbering index is going to reset for each typesetting phase. Could yout show me the example with the actual JavaScript code ?

**Comment by BIKA-C** [comment]
@tani I'am doing a MathJax plugin for vscode, since unfortunately, no owner of existing markdown math plugins is willing to add MathJax support. From the document, it says if the content updates dynamically, I will need to call the [`MathJax.texReset()`](https://docs.mathjax.org/en/latest/web/typeset.html#resetting-automatic-equation-numbering) function. I have extremely limited knowledge on javascript. Here is the import and config: 
```javascript
return {
        extendMarkdownIt(md) {
            return md.use(require("markdown-it-mathjax3"), MathJaxConfig);
        }
    };
```
Config:
```javascript
const MathJaxConfig = {
        tex: {
            packages: ['base', 'ams', 'boldsymbol', 'newcommand', 'unicode', 'color',  'enclose'], // extensions to use
            tagSide: "right", // side for \tag macros
            tagIndent: "0.8em", // amount to indent tags
            multlineWidth: "100%", // width of multline environment
            useLabelIds: false, // use label name rather for ids
            tags: "ams", // or 'ams' or 'all'
            inlineMath: [
                // start/end delimiter pairs for in-line math
                ["$", "$"],
                ["\\(", "\\)"]
            ],
            displayMath: [
                // start/end delimiter pairs for display math
                ["$$", "$$"],
                ["\\[", "\\]"]
            ],
            processEscapes: true, // use \$ to produce a litteral dollar sign
            processEnvironments: false, // process \begin{xxx}...\end{xxx} outside math mode
            processRefs: false, // process \ref{...} outside of math mode,
            maxMacros: 10000,  //maximum number of macro substitutions per expression //10000
            maxBuffer: 15 * 1024 // maximum size for the internal TeX string (5K) //5 * 1024
        },
        asciimath: {
            delimiters: [['<ascii>', '</ascii>'], ['`', '`']]
        },
        MathML: {
            parseAs: "html", // or 'xml'
            forceReparse: true //Need to set true. Have bug in MathJax 3.0.1
            //forceReparse: false // Force the MathML to be reparsed?
            //   (e.g., for XML parsing in an HTML document)
        },
        HTML: {
            scale: 1, // Global scaling factor for all expressions
            mathmlSpacing: false, // true for MathML spacing rules, false for TeX rules
            exFactor: 0.5, // default size of ex in em units when ex size can't be determined
            forceReparse: true
        },
        CHTML: {
            scale: 1, // Global scaling factor for all expressions
            mathmlSpacing: false, // true for MathML spacing rules, false for TeX rules
            exFactor: 0.5, // default size of ex in em units when ex size can't be determined
            forceReparse: true
        },
    };
```
Here is the effect:
![co2](https://user-images.githubusercontent.com/50717946/163668153-7e5fba99-4930-4482-9081-36ab5b47a2a7.gif)

The equation number increments itself for every content update. 

The `here` in the console is from a script that is being executed for every content update. My idea is to just throw the `MathJax.texReset()` in there. Ref: microsoft/vscode#136255
